package com.fung.cms.model;

public class Content {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.content_id
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.content_type
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.content_title
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    private String contentTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.sum_img
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    private String sumImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.content_link
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    private String contentLink;
    
    
    private String sumDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.full_content
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    private String fullContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.sum_desc
     *
     * @return the value of tb_content.sum_desc
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public String getSumDesc() {
        return sumDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.sum_desc
     *
     * @param sumDesc the value for tb_content.sum_desc
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public void setSumDesc(String sumDesc) {
        this.sumDesc = sumDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.full_content
     *
     * @return the value of tb_content.full_content
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public String getFullContent() {
        return fullContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.full_content
     *
     * @param fullContent the value for tb_content.full_content
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public void setFullContent(String fullContent) {
        this.fullContent = fullContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.content_id
     *
     * @return the value of tb_content.content_id
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.content_id
     *
     * @param contentId the value for tb_content.content_id
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.content_type
     *
     * @return the value of tb_content.content_type
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.content_type
     *
     * @param contentType the value for tb_content.content_type
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.content_title
     *
     * @return the value of tb_content.content_title
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public String getContentTitle() {
        return contentTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.content_title
     *
     * @param contentTitle the value for tb_content.content_title
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public void setContentTitle(String contentTitle) {
        this.contentTitle = contentTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.sum_img
     *
     * @return the value of tb_content.sum_img
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public String getSumImg() {
        return sumImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.sum_img
     *
     * @param sumImg the value for tb_content.sum_img
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public void setSumImg(String sumImg) {
        this.sumImg = sumImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.content_link
     *
     * @return the value of tb_content.content_link
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public String getContentLink() {
        return contentLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.content_link
     *
     * @param contentLink the value for tb_content.content_link
     *
     * @mbggenerated Thu Jun 05 23:12:41 GMT+08:00 2014
     */
    public void setContentLink(String contentLink) {
        this.contentLink = contentLink;
    }
    
    
    
    
}